### ISSUE TITLE
Vagrant setup not working

### ISSUE THREAD

**Issue by smolz** [hoelsner/network-config-generator#2]
I have tried using the vagrant file on MacOS and linux 14.04 server.  Both return the same error:

==> ncg: Use of uninitialized value $answer in chop at /usr/sbin/adduser line 589.
==> ncg: Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 590.
==> ncg: Is the information correct? [Y/n] 
==> ncg: Adding user `ncg' to group `sudo' ...
==> ncg: Adding user ncg to group sudo
==> ncg: Done.
==> ncg: copy source files to /var/www/network_config_generator
==> ncg: rm: 
==> ncg: cannot remove ‘/var/www/network_config_generator/network_config_generator.key’
==> ncg: : No such file or directory
==> ncg: rm: cannot remove ‘/var/www/network_config_generator/ftp_user.key’: No such file or directory
==> ncg: rm: 
==> ncg: stage the Network Configuration Generator Web service...
==> ncg: cannot remove ‘/var/www/network_config_generator/log/application.log’: No such file or directory
==> ncg: rm: cannot remove ‘/var/www/network_config_generator/*.db’: No such file or directory
==> ncg: [DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
==> ncg: make sure become_method is 'sudo' (default).
==> ncg: This feature will be removed in a 
==> ncg: future release. Deprecation warnings can be disabled by setting 
==> ncg: deprecation_warnings=False in ansible.cfg.
==> ncg: 
==> ncg: PLAY [localhost] ***************************************************************
==> ncg: 
==> ncg: TASK [update apt cache] ********************************************************
==> ncg: ok: [localhost]
==> ncg: 
==> ncg: TASK [install packages] ********************************************************
==> ncg: failed: [localhost] (item=[u'python3.5', u'python3-pip', u'build-essential', u'python-dev', u'python3-dev', u'python-virtualenv', u'nginx', u'redis-server', u'shellinabox']) => {"failed": true, "item": ["python3.5", "python3-pip", "build-essential", "python-dev", "python3-dev", "python-virtualenv", "nginx", "redis-server", "shellinabox"], "msg": "No package matching 'python3.5' is available"}
==> ncg: 	to retry, use: --limit @/var/www/network_config_generator/deploy/setup.retry
==> ncg: 
==> ncg: PLAY RECAP *********************************************************************
==> ncg: localhost                  : ok=1    changed=0    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by slugfish** [comment]
I may be off but it might be that you've got python3.5 listed and your repo doesn't have that file available. I'd check n see what the most current version of python3 that is availbe in your repo is called and adjust the variable in the playbook.     -but who knows, I'm a dummy

**Comment by hoelsner** [comment]
Hello @smolz,

I agree with @slugfish, python 3.5 is not available as far as i know in Ubuntu 14.04. If you change it back to 3.4 it should work. The better solution is to use a Ubuntu 16.04 server (which is the required platform on the master branch). I noticed that the readme includes the wrong Ubuntu version, which is now fixed.

Greetings Henry

**Comment by smolz** [comment]
Thanks!
