### ISSUE TITLE
Question on templates

### ISSUE THREAD

**Issue by dpflick** [hoelsner/network-config-generator#4]
Thanks so much for this work.  It is AWESOME!
I am very new to Python (3rd day) and my only previous "programming" experience is with Cisco equipment (20+ years).  I already have a working template with conditionals but I want to take this to the next level of automation!

My goal is for anyone to fill out a spreadsheet and generate evergreen configs for dozens of routers and/or firewalls at a time.

While it is easy to create a CSV will all the possible dynamic options, I would like to know if there is an easy way to add a list of global options separately from the router list so the CSV would be smaller and more easily maintained.  For example:

Router CSV file:
hostname,MGMT_IP
Router1,1.1.1.1
Router2,2.2.2.2
etc.....

Global file:
DOMAIN,domain.com
NTP,[1.2.3.4,1.2.3.5]
NETMON,[4.5.6.7,5.6.7.8]

I was thinking I could define globals at the top of the template and I am looking into that now but I was wondering if it would be possible to keep them separate so that I can use the same global for routers and firewalls and hosts (which all use different templates due to the vast differences in platforms).

I was hoping that you could suggest a good method to integrate this into your system like which file I should modify or if putting the variables in the template would be appropriate and I will try to figure out the rest.  

Finally, is it possible to add modules to use within mako templates?  I was thinking about doing the following but did not want to mess things up:
pip install netaddr
Add "import netaddr" to confgen.py
Would I then be able to use netaddr functions in the template like:
IPNetwork(LAN_IP).address

**Comment by hoelsner** [comment]
Hello dpflick, 

currently, there is no easy way to define a common set of variables for a group of devices. It's also a quite large change because an extension of the schema is required (you need somehow add the variable definition to the project model, add it to the user interface etc.). 

Regarding your seconds question: If you plan to do more with IP addresses, you don't need the `netaddr` module because it is running python 3.4. This version contains an `ipaddress` module by default (see https://docs.python.org/release/3.4.7/library/ipaddress.html?highlight=ipaddress#module-ipaddress). 

The following snippet shows how to define a custom function including python code within a mako template (written in plain python):

```python
from mako.template import Template


MAKO_TEMPLATE_STRING = """\
<%def name="get_netmask(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).netmask
%></%def>
<%def name="get_address(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).ip
%></%def>
! Variable Input: ${data}
${get_address(data)} ${get_netmask(data)}
"""

if __name__ == "__main__":
    print(Template(MAKO_TEMPLATE_STRING).render(data="192.168.1.1/24"))
```
**Output:**
<pre>
! Variable Input: 192.168.1.1/24
192.168.1.1 255.255.255.0
</pre>

You can use the content of the template variable from the snippet direct in your mako template (see http://docs.makotemplates.org/en/latest/defs.html and http://docs.makotemplates.org/en/latest/syntax.html#python-blocks for additional information), but you need to call your variable at least once directly to get the variable detection mechanism working. Please let me know if this works for you. 

Greetings, Henry

**Comment by dpflick** [comment]
I found a work-around for the globals by building the CSV from Excel.  I have a worksheet with the globals, and a second worksheet for the router variables and I statically link the cells in the router sheet to the global sheet.  Then I just save the active sheet as a CSV and I have a working input file.  By referencing the cell like "=Globals!A$2" I am able to lock the row to "2" so I can just drag down copy the cell in the router sheet to get the same reference.  This allows me to change the cell on the Globals sheet and that automatically fills in any number of lines in the router sheet with identical information.  Not elegant but usable.  :-) 

Thank you so much for the code sample! From what you sent, I was able to figure out how to get the output I needed (almost) from the ipaddress docs.  I was able to do the following from a python prompt:
```
>>> MAKO_TEMPLATE_STRING = """\
... <%def name="get_netmask(ip_string)"><%
...     import ipaddress
...     return ipaddress.IPv4Interface(ip_string).netmask
... %></%def>
... <%def name="get_address(ip_string)"><%
...     import ipaddress
...     return ipaddress.IPv4Interface(ip_string).ip
... %></%def>
... <%def name="get_subnet(ip_string)"><%
...     import ipaddress
...     return ipaddress.IPv4Interface(ip_string).network
... %></%def>
... <%def name="get_hostmask(ip_string)"><%
...     import ipaddress
...     return ipaddress.IPv4Interface(ip_string).hostmask
... %></%def>
... ! Variable Input: ${data}
... ${get_address(data)} ${get_netmask(data)} ${get_subnet(data)} ${get_hostmask(data)}
... """
>>> print(Template(MAKO_TEMPLATE_STRING).render(data="192.168.1.1/25"))

! Variable Input: 192.168.1.1/25
192.168.1.1 255.255.255.128 192.168.1.0/25 0.0.0.127
```

This is getting me closer but the reason I was trying to use netaddr instead of ipaddress is that I could not find any way of getting ipaddress to return just the network address without the subnet included.  I read the ipaddress docs and did a few searches on Google but could not find any way to strip the /25 from the ${get_subnet(data))  output above.   I need to be able to create BGP network entries so I need the network, then the word "mask" then the subnet.

Also, when I tried to put this into your network config tool, it gives me an error.

```
<%def name="get_netmask(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).netmask
%></%def>
<%def name="get_address(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).ip
%></%def>
! Variable Input: ${data}
${get_address(data)} ${get_netmask(data)}
```
I get "Invalid template, please correct the following error: Template Attribute error: Expected 4 octets in 'test'".  Do you see anything glaringly wrong here?
Once I am able to get the code above working, my guess is that I would reference these in the template like this?

CSV contains variables BGP_AS and LAN_IP with values of '65530" and '192.168.1.1/25' respectively.

My template would have a format like:
router bgp ${ BGP_AS}
 network ${get_subnet(data)} mask ${get_netmask(data)}

**Comment by dpflick** [comment]
So I got a bit farther....  If I put ONLY this into the template, it validates:

```
<%def name="get_netmask(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).netmask
%></%def>
<%def name="get_address(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).ip
%></%def>
<%def name="get_network(ip_string)"><%
    import ipaddress
    return ipaddress.IPv4Interface(ip_string).network
%></%def>

```
But when I try any type of reference, I get an error.
```
! Variable Input: ${LAN_IP}  <--I tried with and without this line
${get_address(LAN_IP)}  <--The template does not seem to like these references.
${get_netmask(LAN_IP)}
${get_subnet(LAN_IP)}
```
One of the searches suggested using "strict_undefined" but all I see is a way to call that from an API and putting all different formats of that in the template seem to be a no-go.  I am not sure that strict_undefined would help as from my understanding it would just show me what string was the problem but I know it has to be LAN_IP since only adding that line causes the halt.

**Comment by dpflick** [comment]
I tried simplifying it a bit but I am still stuck.  I have posted to the Mako group and they suggested this format but it still fails in the network-config-generator tool

```
<%!
    ## python module-level code
    import ipaddress
%>


<%def name="get_address(LAN_IP)">
    <%
    return ipaddress.IPv4Interface(LAN_IP).ip
    %>
</%def>


${get_address(LAN_IP)}
```
If I remove the last line (the call) the template is accepted into the tool.

**Comment by dpflick** [comment]
I may have gotten a bit farther.  I tried this for a template:
```
<%!
    ## python module-level code
    import ipaddress
%>


<%def name="get_address(ip_string)">
    <%
    return ipaddress.IPv4Interface(ip_string).ip
    %>
</%def>
! Variable Input: ${LAN_IP}
${get_address(LAN_IP)}
```

and now I get Invalid template, please correct the following error: Template Attribute error: Expected 4 octets in 'test'

Since 'test' is no where in my template, I think this is a bug in the front end code.  Am I on the right track?

**Comment by dpflick** [comment]
Here is the code to return a network without the mask:
>>> import ipaddress
>>> ipaddress.ip_interface("192.168.99.129/25").network
IPv4Network('192.168.99.128/25')
>>> ipaddress.ip_interface("192.168.99.129/25").network.network_address
IPv4Address('192.168.99.128')
>>> ipaddress.ip_interface("192.168.99.154/30").network.network_address
IPv4Address('192.168.99.152')

**Comment by hoelsner** [comment]
Hi @dpflick, 

I think I found the root cause of the problem. The issue is not the template itself, it's more the validation function for the HTML form when creating the configuration template.

**Solution:** It would work if you add an error handling to the python section of the template.

```mako
<%!
    ## python module-level code
    import ipaddress
%>
<%def name="get_address(ip_string)">
    <%
    try:
        return ipaddress.IPv4Interface(ip_string).ip
    except Exception:
        return "FAIL_OR_EMPTY"
    %>
</%def>
! Variable Input: ${LAN_IP}
${get_address(LAN_IP)}
```

**Explanation:** During the server-side validation of the HTML form, the configuration template is rendered with a dummy parameter set to verify the syntax (see file `app/forms.py`, class `ConfigTemplateForm`). Your config template is validated with the following parameter set during the form validation:

```json
{
    "hostname": "test",
    "LAN_IP": "test"
}
```

Within the python section of the template, the class `IPv4Interface` will throw an exception due to the invalid value during the validation process. Therefore, the server rejects the form data and the template is not created. 

Hope that helps. 

Greetings, Henry

**Comment by dpflick** [comment]
Awesome!  Let me try that out.  Thanks!

**Comment by dpflick** [comment]
That resolved the issue!  Thanks so much for the help!

**Comment by dpflick** [comment]
That worked!  Thanks so much for your help.  I would like to donate to the project if you have a way to do that.

From: Daniel Flick
Sent: Wednesday, October 18, 2017 3:09 PM
To: hoelsner/network-config-generator <reply@reply.github.com>; hoelsner/network-config-generator <network-config-generator@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [hoelsner/network-config-generator] Question on templates (#4)

Awesome!  Let me try that out.  Thanks!
