### ISSUE TITLE
can't add more than one Project + can't add Template Value set on Raspberry Pi 

### ISSUE THREAD

**Issue by mitja-eemobility** [hoelsner/network-config-generator#9]
Hey, 

i am running your config generator on a Raspberry Pi in our local network. I can access the network configuration generator via browser. 
issue #1: if i've added a Project i can't add another Project. It just does nothing. 
issue #2: more importantly if i created my Template in the Project it shows the variables used within the template. ( I used hostname ${ hostname } interface ${ management_interface }ip address ${ management_ip } ${ management_subnetmask } ) for testing purposes. If i try to add a Template Value Set, i type in the Hostname and save.
Now when i enter some variables and click on "save" it just clears the input lines and nothing happens. Also i can not edit the file.
Furthermore If i add another  new Config Template i can not change the Hostname of that Template and therefore can't create the first Template Value Set.

Maybe you can somehow help me out with this issue. 

Kind regards
Mitja

**Comment by hoelsner** [comment]
Hi, 

I think this behavior is related to an issue with Flask-WTForms and SQLAlchemy (according https://github.com/wtforms/wtforms-sqlalchemy/issues/9 and https://github.com/wtforms/wtforms/issues/373). 

Can you please try to downgrade SQLAlchemy on your server to Version 1.1.18? The `virtual-env` for the application is located at `/var/www/network_config_generator/venv/`. The following commands should replace the installed SQLAlchemy version:

```
cd /var/www/network_config_generator
venv/bin/pip3 uninstall SQLAlchemy
venv/bin/pip3 install SQLAlchemy==1.1.18
sudo systemctl restart gunicorn-network_config_generator
```

If this works, I will update the requirements.txt of the project to avoid this issue in the future.

Greetings, Henry

**Comment by sjhaddow** [comment]
Hi Henry,

That worked perfectly, many thanks.
